### PR TITLE
Add raspberry pi guide

### PR DESCRIPTION
**Pull request by jpihl**
@petya2164 do you have any comments/improvements to the raspberry pi guide?

### CODE REVIEW

**Comment by jpihl** [comment]
@petya2164 ready for merge?

**Comment by petya2164** [comment]
@jpihl I am not sure if the readme is the right place for this guide.
Should we put this in a separate document?

**Comment by jpihl** [comment]
I thought about that, but it wanted it to be in the table of content. But maybe we could just as well move it to a separate file. What do you think?

**Comment by petya2164** [comment]
We can still include it in the TOC, under the "Building from Source" section.
Let me demonstrate that ;)

**Comment by jpihl** [comment]
Sounds good.. We should do that an merge this :)

**Pull request merged**
